export const PROGRAMS = [
  {
    slug: 'pendidikan-awal-kanak-kanak',
    name: 'Pendidikan Awal Kanak-Kanak',
    level: 'Diploma Kemahiran Malaysia',
    code: 'T982:001-3:2017 / T982:001-4:2018',
    status: 'active',
    icon: '\u{1F476}',
    color: 'from-amber-500 to-yellow-400',
    description: 'Program ini akan melatih pelajar dalam penjagaan dan pendidikan awal kanak-kanak bagi membentuk pendidik yang penyayang dan berkualiti.',
    highlights: ['Menyediakan laluan ke bidang pendidikan awal profesional', 'Pembelajaran berasaskan praktikal dengan bimbingan tenaga pengajar berpengalaman'],
    careers: ['Guru Taska', 'Penyelia Taska', 'Pembantu Guru Taska', 'Pengusaha Taska', 'Pensyarah'],
    brochure: 'https://drive.google.com/file/d/1mXN7fJ_o9daoUrq3_bLgCTuAXR273zVx/view?usp=sharing',
  },
  {
    slug: 'multimedia',
    name: 'Multimedia',
    level: 'Diploma Kemahiran Malaysia',
    code: 'J582-001-3:2019 / IT-070-4:2011',
    status: 'active',
    icon: '\u{1F3A8}',
    color: 'from-purple-600 to-indigo-500',
    description: 'Program ini akan memberi kemahiran dalam penghasilan kandungan digital dan multimedia menggunakan teknologi kreatif terkini.',
    highlights: ['Gabungan pembelajaran teori dan projek kreatif sebenar', 'Persediaan kukuh untuk kerjaya dalam industri digital dan kreatif'],
    careers: ['Graphic Designer', 'Web Designer / Web Developer', 'Editor Multimedia', 'Motion Graphics Artist', 'Digital Content Creator'],
    brochure: null,
  },
  {
    slug: 'elektrik',
    name: 'Pemasangan & Penyelenggaraan Elektrik',
    level: 'Sijil Kemahiran Malaysia',
    code: 'F432-005-2:2019 / F432-005-3:2019',
    status: 'active',
    icon: '⚡',
    color: 'from-yellow-500 to-orange-400',
    description: 'Program ini dapat membangunkan kemahiran asas dan lanjutan dalam sistem pendawaian elektrik, penyelenggaraan, dan keselamatan kerja mengikut piawaian industri (Satu Fasa & Tiga Fasa).',
    highlights: ['Pembelajaran berasaskan bengkel sebenar', 'Peluang pekerjaan luas dalam bidang teknikal dan penyelenggaraan'],
    careers: ['Juruteknik Elektrik', 'Juruelektrik', 'Juruteknik Penyelenggaraan', 'Kontraktor Elektrik'],
    brochure: null,
  },
  {
    slug: 'pra-sekolah',
    name: 'Pentadbiran & Pendidikan Pra-Sekolah',
    level: 'Diploma Kemahiran Malaysia',
    code: 'J582-001-3:2019 / IT-070-4:2011',
    status: 'active',
    icon: '\u{1F3EB}',
    color: 'from-green-500 to-teal-400',
    description: 'Program ini akan membekalkan pelajar dengan kemahiran mengajar, merancang aktiviti dan mengurus kelas prasekolah secara kreatif dan efektif.',
    highlights: ['Peluang untuk menjadi pendidik prasekolah bertauliah', 'Pembelajaran yang menyeronokkan dengan pendekatan kreatif'],
    careers: ['Penyelia Prasekolah', 'Penolong Pengetua', 'Penyelaras Program Prasekolah', 'Pegawai Program Awal Kanak-Kanak'],
    brochure: null,
  },
  {
    slug: 'kulinari',
    name: 'Kulinari',
    level: 'Diploma Kemahiran Malaysia',
    code: 'Akan Diumumkan',
    status: 'coming_soon',
    icon: '\u{1F468}‍\u{1F373}',
    color: 'from-red-500 to-orange-500',
    description: 'Program ini akan dibuka untuk membina kemahiran asas dalam seni masakan, pengurusan dapur dan penyediaan makanan profesional.',
    highlights: ['Latihan berasaskan dapur sebenar', 'Peluang kerjaya dalam industri makanan dan hospitaliti'],
    careers: ['Tukang Masak', 'Pembantu Kulinari', 'Penyelia Dapur', 'Usahawan Makanan'],
    brochure: null,
  },
  {
    slug: 'cyber-security',
    name: 'Cyber Security',
    level: 'Diploma Kemahiran Malaysia',
    code: 'Akan Diumumkan',
    status: 'coming_soon',
    icon: '\u{1F510}',
    color: 'from-blue-600 to-cyan-500',
    description: 'Program ini akan dibuka untuk memberi asas dalam keselamatan siber dan perlindungan sistem maklumat daripada ancaman digital.',
    highlights: ['Latihan selaras dengan keperluan industri teknologi semasa', 'Permintaan tinggi dalam pasaran kerja digital'],
    careers: ['Penganalisis Keselamatan Siber', 'Juruteknik Forensik Komputer', 'Juruteknik Pertahanan Siber', 'Jurutera Sistem Keselamatan'],
    brochure: null,
  },
]

export const PPT_PROGRAMS = [
  { name: 'Diploma Pentadbiran Pejabat', form: 'https://forms.gle/PfBsTa8cbjtiJ2nKA' },
  { name: 'Diploma Pendidikan Awal Kanak-Kanak', form: 'https://forms.gle/yPDuN65cG4KE5GWw6' },
  { name: 'Diploma Pendidikan Pra-Sekolah', form: 'https://forms.gle/sxx4PhjAhzdvSHbF7' },
]

export const CONTACT = {
  address: 'Level 4, Lipis Centrepoint, Jalan Pekeliling, 27200 Kuala Lipis, Pahang',
  phone1: '010 808 6630',
  phone2: '016 446 6630',
  whatsapp: 'https://api.whatsapp.com/send?phone=60164466630&text=Saya%20nak%20tahu%20lebih%20tentang%20program%20di%20TVET%20Lipis!',
  email: 'admission.tvetlipis@gmail.com',
  tiktok: 'https://www.tiktok.com/@tvet_lipis',
  maps: 'https://maps.app.goo.gl/BSa7uxTcHobB7bhBA',
  hours: 'Isnin–Sabtu: 9:00 pagi – 6:00 petang',
}
